name: ETF Investment Assistant

on:
  workflow_dispatch:   # cron-job.org 或手动触发

permissions:
  contents: write       # 允许保存 record.json

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4

      # Python环境
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 安装依赖
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install akshare requests pandas

      # 运行ETF助手
      - name: Run ETF Assistant
        env:
          SERVERCHAN_KEY: ${{ secrets.SERVERCHAN_KEY }}
        run: |
          python investment_alert.py

      # 查看record状态
      - name: Check record.json
        run: |
          ls -l record.json
          git status

      # 保存record.json变化
      - name: Save record.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add record.json

          git commit -m "Update ETF record" || echo "No record changes"

          git push
