name: ETF Investment Assistant

on:

  schedule:

    # 北京时间11:29日报
    - cron: "29 3 * * 1-5"

    # 北京时间14:59
    - cron: "59 6 * * 1-5"


  workflow_dispatch:


jobs:

  run-etf:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"


      - name: Install packages
        run: |
          pip install akshare requests


      - name: Run ETF Assistant
        env:
          SERVERCHAN_KEY: ${{ secrets.SERVERCHAN_KEY }}

        run: |
          python investment_alert.py
